# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Package and publish Pushmonolith Cli

on:
  workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Package
      run: dotnet pack ./pushmonolith/src/Pushmonolith.Cli/Pushmonolith.Cli.csproj --version-suffix "${{ github.run_number }}"
    - name: Archive package artifacts
      uses: actions/upload-artifact@v4
      with:
        name: archive ${{ github.run_number }}
        path: ./pushmonolith/src/Pushmonolith.Cli/nupkg/*.nupkg
    # - name: Test
    #   run: dotnet test --no-build --verbosity normal
